export const junkyardFactoryAbi = [
  {
    type: 'event',
    name: 'SeriesCreated',
    inputs: [
      { name: 'seriesId', type: 'uint256', indexed: true },
      { name: 'nftCollection', type: 'address', indexed: true },
      { name: 'seriesAddress', type: 'address', indexed: true },
      { name: 'prizePoolAddress', type: 'address', indexed: false },
      { name: 'creator', type: 'address', indexed: false },
      { name: 'price', type: 'uint256', indexed: false },
      { name: 'paymentToken', type: 'address', indexed: false },
      { name: 'maxSupply', type: 'uint256', indexed: false },
      { name: 'startTime', type: 'uint256', indexed: false },
      { name: 'endTime', type: 'uint256', indexed: false },
      { name: 'configGuard', type: 'address', indexed: false },
      { name: 'buyGuard', type: 'address', indexed: false },
      { name: 'oracle', type: 'address', indexed: false },
      { name: 'maxAssetTypesPerOpening', type: 'uint8', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'createSeries',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'nftName', type: 'string' },
      { name: 'nftSymbol', type: 'string' },
      { name: 'price', type: 'uint256' },
      { name: 'paymentToken', type: 'address' },
      { name: 'maxSupply', type: 'uint256' },
      { name: 'startTime', type: 'uint256' },
      { name: 'endTime', type: 'uint256' },
      { name: 'configGuard', type: 'address' },
      { name: 'buyGuard', type: 'address' },
      { name: 'oracle', type: 'address' },
      { name: 'maxAssetTypesPerOpening', type: 'uint8' },
    ],
    outputs: [{ name: 'seriesId', type: 'uint256' }],
  },
] as const;
