export const junkyardSeriesAbi = [
  {
    type: 'function',
    name: 'purchase',
    stateMutability: 'payable',
    inputs: [],
    outputs: [{ name: 'boxId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'open',
    stateMutability: 'payable',
    inputs: [{ name: 'boxId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'boxId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getConfig',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'creator', type: 'address' },
      { name: 'price', type: 'uint256' },
      { name: 'paymentToken', type: 'address' },
      { name: 'maxSupply', type: 'uint256' },
      { name: 'startTime', type: 'uint256' },
      { name: 'endTime', type: 'uint256' },
      { name: 'configGuard', type: 'address' },
      { name: 'buyGuard', type: 'address' },
      { name: 'oracle', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'isConfigLocked',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: 'locked', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getLeftoverPolicy',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'mode', type: 'uint8' },
      { name: 'recipient', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'updateSaleConfig',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'price', type: 'uint256' },
      { name: 'startTime', type: 'uint256' },
      { name: 'endTime', type: 'uint256' },
      { name: 'maxSupply', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setLeftoverPolicy',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'mode', type: 'uint8' },
      { name: 'recipient', type: 'address' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'sweepLeftovers',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
] as const;
